# Generated by Django 6.0.2 on 2026-03-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_goal', models.CharField(max_length=50)),
                ('unit_discription', models.CharField(max_length=50)),
            ],
        ),
    ]
