# Generated by Django 6.0.2 on 2026-03-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_discription',
            new_name='unit_description',
        ),
    ]
