# Generated by Django 6.0.2 on 2026-03-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_unit_discription_unit_unit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=20)),
                ('assignment_weight', models.IntegerField(max_length=3)),
            ],
        ),
    ]
