# Generated by Django 6.0.2 on 2026-03-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_weight',
            field=models.IntegerField(),
        ),
    ]
