# Generated by Django 6.0.2 on 2026-05-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_assignment_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='unit',
        ),
        migrations.CreateModel(
            name='AssignmentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_sets', to='main.unit')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.assignmentset'),
        ),
    ]
